line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
column_width = 120
quote_style = "AutoPreferDouble"
call_parentheses = "None"
space_before_function_call_single_arg = none
space_before_attribute = none
